<?php
$presentation_data = [
        ["./img/tof-1.jpg", "Titre1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque nec lectus eu elit varius dictum eu nec erat. Nullam non ipsum viverra, accumsan justo et, porta lectus. Proin ac tellus suscipit, tempor ex sit amet, consequat magna. Donec ac porta mauris, a pulvinar felis. Sed non odio felis. In ipsum ex, rutrum vitae lobortis vel, pellentesque sit amet velit. Suspendisse vel sapien placerat, posuere mauris a, fermentum felis. Curabitur consequat venenatis ultrices. Quisque ut suscipit arcu, ut auctor dui. Duis sodales, lacus eget vehicula dictum, neque ipsum porta neque, et lobortis lacus arcu eget erat. Sed erat augue, sagittis id ante ut, auctor venenatis orci. Donec blandit quis orci eu molestie. Aliquam volutpat tellus non risus blandit aliquet. Maecenas vel dolor commodo, venenatis felis vel, viverra elit."],
        ["./img/tof-2.jpg", "Titre2","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque nec lectus eu elit varius dictum eu nec erat. Nullam non ipsum viverra, accumsan justo et, porta lectus. Proin ac tellus suscipit, tempor ex sit amet, consequat magna. Donec ac porta mauris, a pulvinar felis. Sed non odio felis. In ipsum ex, rutrum vitae lobortis vel, pellentesque sit amet velit. Suspendisse vel sapien placerat, posuere mauris a, fermentum felis. Curabitur consequat venenatis ultrices. Quisque ut suscipit arcu, ut auctor dui. Duis sodales, lacus eget vehicula dictum, neque ipsum porta neque, et lobortis lacus arcu eget erat. Sed erat augue, sagittis id ante ut, auctor venenatis orci. Donec blandit quis orci eu molestie. Aliquam volutpat tellus non risus blandit aliquet. Maecenas vel dolor commodo, venenatis felis vel, viverra elit."],
        ["./img/tof-3.jpg","Titre3" , "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque nec lectus eu elit varius dictum eu nec erat. Nullam non ipsum viverra, accumsan justo et, porta lectus. Proin ac tellus suscipit, tempor ex sit amet, consequat magna. Donec ac porta mauris, a pulvinar felis. Sed non odio felis. In ipsum ex, rutrum vitae lobortis vel, pellentesque sit amet velit. Suspendisse vel sapien placerat, posuere mauris a, fermentum felis. Curabitur consequat venenatis ultrices. Quisque ut suscipit arcu, ut auctor dui. Duis sodales, lacus eget vehicula dictum, neque ipsum porta neque, et lobortis lacus arcu eget erat. Sed erat augue, sagittis id ante ut, auctor venenatis orci. Donec blandit quis orci eu molestie. Aliquam volutpat tellus non risus blandit aliquet. Maecenas vel dolor commodo, venenatis felis vel, viverra elit."],
        ["./img/tof-4.jpg", "Titr4" , "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque nec lectus eu elit varius dictum eu nec erat. Nullam non ipsum viverra, accumsan justo et, porta lectus. Proin ac tellus suscipit, tempor ex sit amet, consequat magna. Donec ac porta mauris, a pulvinar felis. Sed non odio felis. In ipsum ex, rutrum vitae lobortis vel, pellentesque sit amet velit. Suspendisse vel sapien placerat, posuere mauris a, fermentum felis. Curabitur consequat venenatis ultrices. Quisque ut suscipit arcu, ut auctor dui. Duis sodales, lacus eget vehicula dictum, neque ipsum porta neque, et lobortis lacus arcu eget erat. Sed erat augue, sagittis id ante ut, auctor venenatis orci. Donec blandit quis orci eu molestie. Aliquam volutpat tellus non risus blandit aliquet. Maecenas vel dolor commodo, venenatis felis vel, viverra elit."]
    ];
$games_data = [
    ["./img/Game-1.jpg", "FIFA 22", "PS4, PS5, XBOX ONE, XBOX SERIES"],
    ["./img/Game-2.jpg", "Samurai Shadow", "PS4, PS5, XBOX ONE, XBOX SERIES"],
    ["./img/Game-3.webp", "The Elden Scroll Online", "PS4, PS5, XBOX ONE, XBOX SERIES"],
    ["./img/Game-4.jpg", "Kingdoms of Amalurs", "PS4, PS5, XBOX ONE, XBOX SERIES"],
    ["./img/Game-5.jpg", "Monster Trucks Championship", "PS4, PS5, XBOX ONE, XBOX SERIES"]
];
$consoles_data = ["../img/ps4-logo.svg", "../img/ps5-logo.svg", "../img/xbox-one-logo.svg", "../img/nintendo-logo.svg"];