name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Upload to Server
        uses: peaceiris/actions-gh-pages@v3
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          local-dir: ./ # Répertoire local où se trouvent les fichiers compilés
          server-dir: /public_html/juanvianneynm.com # Répertoire distant sur le serveur

